---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	detect_context_type(detect_context_type)
	process_uploaded_files(process_uploaded_files)
	inject_session_context(inject_session_context)
	route_intent(route_intent)
	get_schema(get_schema)
	generate_sql(generate_sql)
	validate_sql_node(validate_sql_node)
	execute_sql_node(execute_sql_node)
	analyze_result(analyze_result)
	retrieve_context_node(retrieve_context_node)
	synthesize_answer(synthesize_answer)
	compact_and_save_memory(compact_and_save_memory)
	__end__([<p>__end__</p>]):::last
	__start__ --> detect_context_type;
	analyze_result -.-> retrieve_context_node;
	analyze_result -.-> synthesize_answer;
	detect_context_type -.-> inject_session_context;
	detect_context_type -.-> process_uploaded_files;
	execute_sql_node -.-> analyze_result;
	execute_sql_node -.-> generate_sql;
	generate_sql --> validate_sql_node;
	get_schema --> generate_sql;
	inject_session_context --> route_intent;
	process_uploaded_files --> inject_session_context;
	retrieve_context_node --> synthesize_answer;
	route_intent -.-> get_schema;
	route_intent -.-> retrieve_context_node;
	route_intent -.-> synthesize_answer;
	synthesize_answer --> compact_and_save_memory;
	validate_sql_node -.-> execute_sql_node;
	validate_sql_node -.-> generate_sql;
	validate_sql_node -.-> retrieve_context_node;
	validate_sql_node -.-> synthesize_answer;
	compact_and_save_memory --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
